parameters:
  devops_artefact_name: 'DevOps'
  # Version Config
  sourcebranch_name: ''
  raw_version_number: ''
  # Build Config
  test_path: ''
  package_path: ''
  # Deploy Config
  package_feed: ''
  publish_symbols: ''
  # Secret Config
  cosmosdb_secret: false
  cosmosdb_account: ''

jobs:
- template: ../jobs/publish-blob-as-artefact.yml
  parameters:
    Package_RG: $(DevOps.RG)
    Package_storageAccount: $(DevOps.storageAccount)
    Package_Container: $(DevOps.Container)
    Package_File: $(DevOps.File)
    Package_OutputFolder: $(Build.BinariesDirectory)
    Package_OutputArtefact: '${{ parameters.devops_artefact_name }}'

- job: BuildDotNet
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'vs2017-win2016'
  continueOnError: false

  steps:
  - template: ../steps/build-updatebuildnumber-dotnet.yml
    parameters:
      sourcebranch_name: '${{ parameters.sourcebranch_name }}'
      raw_version_number: '${{ parameters.raw_version_number }}'

  - ${{ if eq(parameters.cosmosdb_secret, true) }}:
    - task: Bash@3
      displayName: 'Get: CosmosDB Key and Endpoint'
      inputs:
        targetType: 'filePath'
        filePath: $(Pipeline.Workspace)/${{ parameters.devops_artefact_name }}/Azure/get-cosmosdb-key-endpoint.sh
        arguments: $(CosmosDB.Account)

  - template: ../steps/build-pack-test-dotnet.yml
    parameters:
      test_path: '${{ parameters.test_path }}'
      package_path: '${{ parameters.package_path }}'
      package_feed: '${{ parameters.package_feed }}'

  - template: ../steps/deploy-push-package-symbols.yml
    parameters:
      package_feed: '${{ parameters.package_feed }}'
      publish_symbols: '${{ parameters.publish_symbols }}'
